# Generated by Django 2.0.1 on 2018-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0002_auto_20180328_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
