# Generated by Django 2.0.1 on 2018-03-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0004_auto_20180328_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
