# Generated by Django 2.0.1 on 2018-03-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0006_auto_20180328_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
