# Generated by Django 2.0.1 on 2018-03-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0007_remove_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.SmallIntegerField(choices=[(0, 'read'), (1, 'add'), (2, 'change'), (3, 'delete')]),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '普通'), (1, '会员')]),
        ),
    ]
