# Generated by Django 2.0.1 on 2018-03-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0008_auto_20180328_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tieba',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tieba.TieBa'),
            preserve_default=False,
        ),
    ]
