# Generated by Django 2.0.1 on 2018-03-28 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0012_auto_20180328_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_tieba',
            field=models.ManyToManyField(blank=True, to='tieba.TieBa'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followed_user',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_followed_user_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
