# Generated by Django 2.0.1 on 2018-03-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0013_auto_20180328_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tieba.Article')),
            ],
        ),
    ]
