# Generated by Django 2.0.1 on 2018-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0015_auto_20180328_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='img',
            field=models.ImageField(null=True, upload_to='article/'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='background_img',
            field=models.ImageField(null=True, upload_to='tieba/background'),
        ),
        migrations.AddField(
            model_name='tieba',
            name='head_img',
            field=models.ImageField(null=True, upload_to='tieba/head/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(null=True, upload_to='user/head/'),
        ),
    ]
