# Generated by Django 2.0.1 on 2018-03-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0017_auto_20180329_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
