# Generated by Django 2.0.1 on 2018-03-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0018_auto_20180329_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_whom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tieba.Comment'),
        ),
    ]
