# Generated by Django 2.0.1 on 2018-03-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0019_auto_20180330_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
