# Generated by Django 2.0.1 on 2018-03-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0023_remove_comment_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tieba.Comment'),
        ),
    ]
