# Generated by Django 2.0.1 on 2018-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0024_comment_to_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_whom',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
