# Generated by Django 2.0.1 on 2018-03-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0025_comment_to_whom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_whom',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
