# Generated by Django 2.0.1 on 2018-04-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tieba', '0026_auto_20180330_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_whom',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tieba',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
